name: CI
on:
  workflow_call:
    inputs:
      ref:
        type: string
        default: ''
jobs:
  ci:
    uses: RogueOneEcho/ci/.github/workflows/docker.yml@v1
    with:
      docker-image: rogueoneecho/preflight
      build-context: src
      grype-args: ''
      ref: ${{ inputs.ref }}
    secrets: inherit
