name: Release
on:
  workflow_dispatch:
    inputs:
      ref:
        type: string
        required: true
        description: Commit SHA or version tag
permissions:
  actions: write
  contents: write
  packages: write
  id-token: write
jobs:
  fast-forward:
    uses: RogueOneEcho/ci/.github/workflows/ff-release.yml@v1
    with:
      ref: ${{ inputs.ref }}
  ci:
    needs: fast-forward
    if: needs.fast-forward.outputs.pushed == 'true'
    uses: ./.github/workflows/ci.yml
    with:
      ref: ${{ needs.fast-forward.outputs.ref }}
    secrets: inherit
